### ISSUE TITLE
ImportError: cannot import name FrontendEditableAdmin

### ISSUE THREAD

**Issue by youyix** [aldryn/aldryn-blog#40]
I got an import error of FrontendEditableAdmin in admin.py at line12.  Could any body help me to fix it?  
Below is my settings,
Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/en/

Django Version: 1.5.5
Python Version: 2.7.3
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'cms',
 'mptt',
 'menus',
 'south',
 'sekizai',
 'easy_thumbnails',
 'reversion',
 'django_select2',
 'hvad',
 'djangocms_text_ckeditor',
 'filer',
 'taggit',
 'aldryn_blog')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.doc.XViewMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'cms.middleware.page.CurrentPageMiddleware',
 'cms.middleware.user.CurrentUserMiddleware',
 'cms.middleware.toolbar.ToolbarMiddleware',
 'cms.middleware.language.LanguageCookieMiddleware')

Traceback:
File "/home/youyix/djangoWorkspace/Dcms/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
1.                     response = middleware_method(request)
   File "/home/youyix/djangoWorkspace/Dcms/env/local/lib/python2.7/site-packages/django/middleware/locale.py" in process_request
2.         check_path = self.is_language_prefix_patterns_used()
   File "/home/youyix/djangoWorkspace/Dcms/env/local/lib/python2.7/site-packages/django/middleware/locale.py" in is_language_prefix_patterns_used
3.         for url_pattern in get_resolver(None).url_patterns:
   File "/home/youyix/djangoWorkspace/Dcms/env/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in url_patterns
4.         patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
   File "/home/youyix/djangoWorkspace/Dcms/env/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in urlconf_module
5.             self._urlconf_module = import_module(self.urlconf_name)
   File "/home/youyix/djangoWorkspace/Dcms/env/local/lib/python2.7/site-packages/django/utils/importlib.py" in import_module
6.     **import**(name)
   File "/home/youyix/djangoWorkspace/Dcms/asite/asite/urls.py" in <module>
7. admin.autodiscover()
   File "/home/youyix/djangoWorkspace/Dcms/env/local/lib/python2.7/site-packages/django/contrib/admin/**init**.py" in autodiscover
8.             import_module('%s.admin' % app)
   File "/home/youyix/djangoWorkspace/Dcms/env/local/lib/python2.7/site-packages/django/utils/importlib.py" in import_module
9.     **import**(name)
   File "/home/youyix/djangoWorkspace/Dcms/env/local/lib/python2.7/site-packages/aldryn_blog/admin.py" in <module>
10. from cms.admin.placeholderadmin import FrontendEditableAdmin

Exception Type: ImportError at /en/
Exception Value: cannot import name FrontendEditableAdmin

**Comment by byronharvey24** [comment]
Hey this doesn't work with django-cms 3.1, however, it does work with django-cms 3.0.11

**Comment by azuax** [comment]
I found the solution. It's very simple. In my case I was using sqlite, but the documentation say it's not allowed https://github.com/aldryn/aldryn-blog#manual-installation
